/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.frauddetector.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class FraudAlert extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {

  public enum FraudPattern {
    FREQUENT_CALLS,
    NPS_ESCALATION,
    ANOMALOUS_DURATION
  }

  public enum AlertSeverity {
    HIGH,
    MEDIUM,
    LOW
  }

  private static final long serialVersionUID = -6283749201847563821L;

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
    "{\"type\":\"record\",\"name\":\"FraudAlert\",\"namespace\":\"com.example.frauddetector.avro\"," +
    "\"fields\":[{\"name\":\"callId\",\"type\":\"string\"}," +
    "{\"name\":\"phone\",\"type\":\"string\"}," +
 "{\"name\":\"pattern\",\"type\":{\"type\":\"enum\",\"name\":\"FraudPattern\",\"symbols\":[\"FREQUENT_CALLS\",\"NPS_ESCALATION\",\"ANOMALOUS_DURATION\"]}}," +
    "{\"name\":\"count\",\"type\":\"int\"}," +
    "{\"name\":\"timestamp\",\"type\":\"string\"}," +
    "{\"name\":\"severity\",\"type\":{\"type\":\"enum\",\"name\":\"AlertSeverity\",\"symbols\":[\"HIGH\",\"MEDIUM\",\"LOW\"]}}]}"
  );

  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FraudAlert> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FraudAlert> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  public static BinaryMessageEncoder<FraudAlert> getEncoder() {
    return ENCODER;
  }

  public static BinaryMessageDecoder<FraudAlert> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   */
  public static BinaryMessageDecoder<FraudAlert> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /** Statically resolved by Avro */
  private static org.apache.avro.util.Utf8 callId$ = new org.apache.avro.util.Utf8("");
  private static org.apache.avro.util.Utf8 phone$ = new org.apache.avro.util.Utf8("");

  public com.example.frauddetector.avro.FraudAlert.FraudPattern pattern$;
  public int count$;
  public org.apache.avro.util.Utf8 timestamp$ = new org.apache.avro.util.Utf8("");
  public com.example.frauddetector.avro.FraudAlert.AlertSeverity severity$;

  /** Default constructor */
  public FraudAlert() {
    set$index(0, null);
    set$index(1, null);
    set$index(2, null);
    set$index(3, 0);
    set$index(4, null);
    set$index(5, null);
  }

  /** All-args constructor */
  public FraudAlert(
      org.apache.avro.util.Utf8 callId,
      org.apache.avro.util.Utf8 phone,
      com.example.frauddetector.avro.FraudAlert.FraudPattern pattern,
      int count,
      org.apache.avro.util.Utf8 timestamp,
      com.example.frauddetector.avro.FraudAlert.AlertSeverity severity) {
    this.callId$ = callId;
    this.phone$ = phone;
    this.pattern$ = pattern;
    this.count$ = count;
    this.timestamp$ = timestamp;
    this.severity$ = severity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  public Object get(int field$) {
    switch (field$) {
    case 0: return callId$;
    case 1: return phone$;
    case 2: return pattern$;
    case 3: return count$;
    case 4: return timestamp$;
    case 5: return severity$;
    default:
      throw new AvroRuntimeException("Bad index " + field$ + " has no corresponding field");
    }
  }

  public void put(int field$_, Object value_) {
    switch (field$_) {
    case 0: this.callId$ = (org.apache.avro.util.Utf8)value_; break;
    case 1: this.phone$ = (org.apache.avro.util.Utf8)value_; break;
    case 2: this.pattern$ = (com.example.frauddetector.avro.FraudAlert.FraudPattern)value_; break;
    case 3: this.count$ = (Integer)value_; break;
    case 4: this.timestamp$ = (org.apache.avro.util.Utf8)value_; break;
    case 5: this.severity$ = (com.example.frauddetector.avro.FraudAlert.AlertSeverity)value_; break;
    default:
      throw new AvroRuntimeException("Bad index " + field$_ + " has no corresponding field");
    }
  }

  /** Get the value of the 'callId' field */
  public org.apache.avro.util.Utf8 getCallId() {
    return callId$;
  }

  /** Set the value of the 'callId' field */
  public void setCallId(org.apache.avro.util.Utf8 value) {
    this.callId$ = value;
  }

  /** Get the value of the 'phone' field */
  public org.apache.avro.util.Utf8 getPhone() {
    return phone$;
  }

  /** Set the value of the 'phone' field */
  public void setPhone(org.apache.avro.util.Utf8 value) {
    this.phone$ = value;
  }

  /** Get the value of the 'pattern' field */
  public com.example.frauddetector.avro.FraudAlert.FraudPattern getPattern() {
    return pattern$;
  }

  /** Set the value of the 'pattern' field */
  public void setPattern(com.example.frauddetector.avro.FraudAlert.FraudPattern value) {
    this.pattern$ = value;
  }

  /** Get the value of the 'count' field */
  public int getCount() {
    return count$;
  }

  /** Set the value of the 'count' field */
  public void setCount(int value) {
    this.count$ = value;
  }

  /** Get the value of the 'timestamp' field */
  public org.apache.avro.util.Utf8 getTimestamp() {
    return timestamp$;
  }

  /** Set the value of the 'timestamp' field */
  public void setTimestamp(org.apache.avro.util.Utf8 value) {
    this.timestamp$ = value;
  }

  /** Get the value of the 'severity' field */
  public com.example.frauddetector.avro.FraudAlert.AlertSeverity getSeverity() {
    return severity$;
  }

  /** Set the value of the 'severity' field */
  public void setSeverity(com.example.frauddetector.avro.FraudAlert.AlertSeverity value) {
    this.severity$ = value;
  }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null) return false;
    FraudAlert other = (FraudAlert) o;
    if (this.callId$ == null) {
      if (other.callId$ != null) return false;
    } else {
      if (!this.callId$.toString().equals(other.callId$.toString())) return false;
    }
    if (this.phone$ == null) {
      if (other.phone$ != null) return false;
    } else {
      if (!this.phone$.toString().equals(other.phone$.toString())) return false;
    }
    if (this.pattern$ != other.pattern$) return false;
    if (this.count$ != other.count$) return false;
    if (this.timestamp$ == null) {
      if (other.timestamp$ != null) return false;
    } else {
      if (!this.timestamp$.toString().equals(other.timestamp$.toString())) return false;
    }
    if (this.severity$ != other.severity$) return false;
    return true;
  }

  public int hashCode() {
    return (
      (this.callId$ == null ? 0 : this.callId$.toString().hashCode()) * 31 +
      (this.phone$ == null ? 0 : this.phone$.toString().hashCode()) * 31 +
      ((this.pattern$ == null) ? 0 : this.pattern$.hashCode()) * 31 +
      this.count$ * 31 +
      (this.timestamp$ == null ? 0 : this.timestamp$.toString().hashCode()) * 31 +
      ((this.severity$ == null) ? 0 : this.severity$.hashCode())
    );
  }
}
