apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Grafana
    type: grafana
    access: proxy
    url: http://grafana:3000
    editable: false
