KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    user_admin="admin-secret"
    user_schema-registry="sr-secret"
    user_connect="connect-secret";
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret";
};
