KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="kafka_broker"
    password="kafka_broker_secret"
    user_kafka_broker="kafka_broker_secret"
    user_alice="alice_secret"
    user_bob="bob_secret"
    user_charlie="charlie_secret";
};
