/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.callprocessor.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CallEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5122872782560715828L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CallEvent\",\"namespace\":\"com.example.callprocessor.avro\",\"fields\":[{\"name\":\"callId\",\"type\":\"string\"},{\"name\":\"phone\",\"type\":\"string\"},{\"name\":\"duration\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"agentId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"npsScore\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"timestamp\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CallEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CallEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CallEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CallEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CallEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CallEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CallEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CallEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CallEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence callId;
  private java.lang.CharSequence phone;
  private java.lang.Integer duration;
  private java.lang.CharSequence agentId;
  private java.lang.Integer npsScore;
  private java.lang.CharSequence status;
  private java.lang.CharSequence timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CallEvent() {}

  /**
   * All-args constructor.
   * @param callId The new value for callId
   * @param phone The new value for phone
   * @param duration The new value for duration
   * @param agentId The new value for agentId
   * @param npsScore The new value for npsScore
   * @param status The new value for status
   * @param timestamp The new value for timestamp
   */
  public CallEvent(java.lang.CharSequence callId, java.lang.CharSequence phone, java.lang.Integer duration, java.lang.CharSequence agentId, java.lang.Integer npsScore, java.lang.CharSequence status, java.lang.CharSequence timestamp) {
    this.callId = callId;
    this.phone = phone;
    this.duration = duration;
    this.agentId = agentId;
    this.npsScore = npsScore;
    this.status = status;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return callId;
    case 1: return phone;
    case 2: return duration;
    case 3: return agentId;
    case 4: return npsScore;
    case 5: return status;
    case 6: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: callId = (java.lang.CharSequence)value$; break;
    case 1: phone = (java.lang.CharSequence)value$; break;
    case 2: duration = (java.lang.Integer)value$; break;
    case 3: agentId = (java.lang.CharSequence)value$; break;
    case 4: npsScore = (java.lang.Integer)value$; break;
    case 5: status = (java.lang.CharSequence)value$; break;
    case 6: timestamp = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'callId' field.
   * @return The value of the 'callId' field.
   */
  public java.lang.CharSequence getCallId() {
    return callId;
  }


  /**
   * Sets the value of the 'callId' field.
   * @param value the value to set.
   */
  public void setCallId(java.lang.CharSequence value) {
    this.callId = value;
  }

  /**
   * Gets the value of the 'phone' field.
   * @return The value of the 'phone' field.
   */
  public java.lang.CharSequence getPhone() {
    return phone;
  }


  /**
   * Sets the value of the 'phone' field.
   * @param value the value to set.
   */
  public void setPhone(java.lang.CharSequence value) {
    this.phone = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return The value of the 'duration' field.
   */
  public java.lang.Integer getDuration() {
    return duration;
  }


  /**
   * Sets the value of the 'duration' field.
   * @param value the value to set.
   */
  public void setDuration(java.lang.Integer value) {
    this.duration = value;
  }

  /**
   * Gets the value of the 'agentId' field.
   * @return The value of the 'agentId' field.
   */
  public java.lang.CharSequence getAgentId() {
    return agentId;
  }


  /**
   * Sets the value of the 'agentId' field.
   * @param value the value to set.
   */
  public void setAgentId(java.lang.CharSequence value) {
    this.agentId = value;
  }

  /**
   * Gets the value of the 'npsScore' field.
   * @return The value of the 'npsScore' field.
   */
  public java.lang.Integer getNpsScore() {
    return npsScore;
  }


  /**
   * Sets the value of the 'npsScore' field.
   * @param value the value to set.
   */
  public void setNpsScore(java.lang.Integer value) {
    this.npsScore = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.CharSequence getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.CharSequence value) {
    this.timestamp = value;
  }

  /**
   * Creates a new CallEvent RecordBuilder.
   * @return A new CallEvent RecordBuilder
   */
  public static com.example.callprocessor.avro.CallEvent.Builder newBuilder() {
    return new com.example.callprocessor.avro.CallEvent.Builder();
  }

  /**
   * Creates a new CallEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CallEvent RecordBuilder
   */
  public static com.example.callprocessor.avro.CallEvent.Builder newBuilder(com.example.callprocessor.avro.CallEvent.Builder other) {
    if (other == null) {
      return new com.example.callprocessor.avro.CallEvent.Builder();
    } else {
      return new com.example.callprocessor.avro.CallEvent.Builder(other);
    }
  }

  /**
   * Creates a new CallEvent RecordBuilder by copying an existing CallEvent instance.
   * @param other The existing instance to copy.
   * @return A new CallEvent RecordBuilder
   */
  public static com.example.callprocessor.avro.CallEvent.Builder newBuilder(com.example.callprocessor.avro.CallEvent other) {
    if (other == null) {
      return new com.example.callprocessor.avro.CallEvent.Builder();
    } else {
      return new com.example.callprocessor.avro.CallEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CallEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CallEvent>
    implements org.apache.avro.data.RecordBuilder<CallEvent> {

    private java.lang.CharSequence callId;
    private java.lang.CharSequence phone;
    private java.lang.Integer duration;
    private java.lang.CharSequence agentId;
    private java.lang.Integer npsScore;
    private java.lang.CharSequence status;
    private java.lang.CharSequence timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.callprocessor.avro.CallEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.callId)) {
        this.callId = data().deepCopy(fields()[0].schema(), other.callId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.phone)) {
        this.phone = data().deepCopy(fields()[1].schema(), other.phone);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.duration)) {
        this.duration = data().deepCopy(fields()[2].schema(), other.duration);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.agentId)) {
        this.agentId = data().deepCopy(fields()[3].schema(), other.agentId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.npsScore)) {
        this.npsScore = data().deepCopy(fields()[4].schema(), other.npsScore);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing CallEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.callprocessor.avro.CallEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.callId)) {
        this.callId = data().deepCopy(fields()[0].schema(), other.callId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.phone)) {
        this.phone = data().deepCopy(fields()[1].schema(), other.phone);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.duration)) {
        this.duration = data().deepCopy(fields()[2].schema(), other.duration);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.agentId)) {
        this.agentId = data().deepCopy(fields()[3].schema(), other.agentId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.npsScore)) {
        this.npsScore = data().deepCopy(fields()[4].schema(), other.npsScore);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'callId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallId() {
      return callId;
    }


    /**
      * Sets the value of the 'callId' field.
      * @param value The value of 'callId'.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder setCallId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.callId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'callId' field has been set.
      * @return True if the 'callId' field has been set, false otherwise.
      */
    public boolean hasCallId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'callId' field.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder clearCallId() {
      callId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'phone' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhone() {
      return phone;
    }


    /**
      * Sets the value of the 'phone' field.
      * @param value The value of 'phone'.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder setPhone(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.phone = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'phone' field has been set.
      * @return True if the 'phone' field has been set, false otherwise.
      */
    public boolean hasPhone() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'phone' field.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder clearPhone() {
      phone = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * @return The value.
      */
    public java.lang.Integer getDuration() {
      return duration;
    }


    /**
      * Sets the value of the 'duration' field.
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder setDuration(java.lang.Integer value) {
      validate(fields()[2], value);
      this.duration = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'duration' field.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder clearDuration() {
      duration = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'agentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAgentId() {
      return agentId;
    }


    /**
      * Sets the value of the 'agentId' field.
      * @param value The value of 'agentId'.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder setAgentId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.agentId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'agentId' field has been set.
      * @return True if the 'agentId' field has been set, false otherwise.
      */
    public boolean hasAgentId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'agentId' field.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder clearAgentId() {
      agentId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'npsScore' field.
      * @return The value.
      */
    public java.lang.Integer getNpsScore() {
      return npsScore;
    }


    /**
      * Sets the value of the 'npsScore' field.
      * @param value The value of 'npsScore'.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder setNpsScore(java.lang.Integer value) {
      validate(fields()[4], value);
      this.npsScore = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'npsScore' field has been set.
      * @return True if the 'npsScore' field has been set, false otherwise.
      */
    public boolean hasNpsScore() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'npsScore' field.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder clearNpsScore() {
      npsScore = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.CharSequence getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder setTimestamp(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.timestamp = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.example.callprocessor.avro.CallEvent.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CallEvent build() {
      try {
        CallEvent record = new CallEvent();
        record.callId = fieldSetFlags()[0] ? this.callId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.phone = fieldSetFlags()[1] ? this.phone : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.duration = fieldSetFlags()[2] ? this.duration : (java.lang.Integer) defaultValue(fields()[2]);
        record.agentId = fieldSetFlags()[3] ? this.agentId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.npsScore = fieldSetFlags()[4] ? this.npsScore : (java.lang.Integer) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.timestamp = fieldSetFlags()[6] ? this.timestamp : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CallEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CallEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CallEvent>
    READER$ = (org.apache.avro.io.DatumReader<CallEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.callId);

    out.writeString(this.phone);

    if (this.duration == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.duration);
    }

    if (this.agentId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.agentId);
    }

    if (this.npsScore == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.npsScore);
    }

    if (this.status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.status);
    }

    if (this.timestamp == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.timestamp);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.callId = in.readString(this.callId instanceof Utf8 ? (Utf8)this.callId : null);

      this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.duration = null;
      } else {
        this.duration = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.agentId = null;
      } else {
        this.agentId = in.readString(this.agentId instanceof Utf8 ? (Utf8)this.agentId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.npsScore = null;
      } else {
        this.npsScore = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.status = null;
      } else {
        this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.timestamp = null;
      } else {
        this.timestamp = in.readString(this.timestamp instanceof Utf8 ? (Utf8)this.timestamp : null);
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.callId = in.readString(this.callId instanceof Utf8 ? (Utf8)this.callId : null);
          break;

        case 1:
          this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.duration = null;
          } else {
            this.duration = in.readInt();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.agentId = null;
          } else {
            this.agentId = in.readString(this.agentId instanceof Utf8 ? (Utf8)this.agentId : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.npsScore = null;
          } else {
            this.npsScore = in.readInt();
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status = null;
          } else {
            this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.timestamp = null;
          } else {
            this.timestamp = in.readString(this.timestamp instanceof Utf8 ? (Utf8)this.timestamp : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










